### ISSUE TITLE
Open file m3u for listening to live radio doesn't work

### ISSUE THREAD

**Issue by maisondasilva** [huynhsontung/Screenbox#257]
I'm installing it on several people who use VLC, but when opening an m3u file it simply doesn't play the radio station live!

file m3u

#EXTM3U
http://centova17.xxxxxxxx.com.br:8052/;

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/79593b08-7fdd-4ee6-9fd1-a34f3ab69849)

**Comment by huynhsontung** [comment]
Multi stream playlist files such as .m3u will be supported in the next version. It was implemented in #209 but there was a bug so it will need a bit more time before hitting the store release.

**Comment by maisondasilva** [comment]
@huynhsontung Thanks for the update!

**Comment by huynhsontung** [comment]
@maisondasilva The latest version of Screenbox with support for playlist files is now on the store. Can you update the app and try again?

**Comment by maisondasilva** [comment]
@huynhsontung Thanks update, not working

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/0e2f6203-0b2f-4cf7-b24b-909f57e70ffc)

**Comment by huynhsontung** [comment]
@maisondasilva Can you share the m3u file for testing if possible?

**Comment by maisondasilva** [comment]
Sure!

[Ouvir Radio.zip](https://github.com/huynhsontung/Screenbox/files/13730837/Ouvir.Radio.zip)

**Comment by huynhsontung** [comment]
Thank you @maisondasilva. There was a bug in the playlist logic that prevented your file from working. #260 should resolve this issue. Shipping in the next update.

**Comment by maisondasilva** [comment]
From what I see, my computer updated to version 0.11.1 last night but I still can't open the file.

![image](https://github.com/huynhsontung/Screenbox/assets/11423362/d25849e7-7428-4a3c-b0b7-30000691bf22)

**Comment by huynhsontung** [comment]
Sorry for the confusion. It will be fixed in the next version, v0.11.2

**Comment by huynhsontung** [comment]
Screenbox v0.11.2 is now available in the store. Please update the app and try again.

**Comment by maisondasilva** [comment]
@huynhsontung Yes now it works as expected! Thank you and Merry Christmas and New Year with lots of health and success! 🤩🤩
