### ISSUE TITLE
Interface isn't hiding when I go fullscreen

### ISSUE THREAD

**Issue by HotarunIchijou** [huynhsontung/Screenbox#86]
When I press the fullscreen button, it opens in fullscreen, but the interface isn't hiding after 3 seconds delay. It can be fixed with double click to leave fullscreen and double click again to go back to fullscreen 

[Here](https://mega.nz/file/s3gyQLwB#38N1cODEWofQPofE8N0jnVVWpnBzENijnN_gYCVsi9g) is a video example that shows the bug. Also I noticed that if I use a hotkey for opening video in fullscreen (F), this bug doesn't appear.

Btw I like this player too much. It's pretty simmilar with Windows Media Player, but it provides some good and useful features like gestures and good .ass subtitles support (in wmp .ass subtitles overlaps and become unreadable). Also Screenbox more stable and feature-rich than the Rise Media Player. Thank you @huynhsontung for development

**Comment by huynhsontung** [comment]
Glad you like the player!

When you press the fullscreen button, the system focus is now on the button. The logic is when the focus is on any of the control buttons, don't hide the interface since the user might be interacting with it. Welp that assumption is wrong. You can workaround this by single clicking the video surface. I will fix this in the next version.

**Comment by huynhsontung** [comment]
Fixed with #94

**Comment by naveenjohnsonv** [comment]
Hi. Actually, even with the new update, the interface still doesn't hide itself if I interact with elements like the resume progress button or if I resume playback with a mouse click. What seems to make the auto hide work is if I click on the osd panel again (region shown below).

![image](https://github.com/huynhsontung/Screenbox/assets/14140949/299ae597-3956-443d-9fc7-37ab70d7a45a)

**Comment by huynhsontung** [comment]
Oops. That PR introduced a new bug. The next update should fix it. For real this time. ✨

**Comment by HotarunIchijou** [comment]
It's not fixed yet?

**Comment by huynhsontung** [comment]
It should already be fixed. I'm just verifying the fix from users. Reopen due to the bug introduced in #94. Will close once I have sufficient feedback that the issue is resolved.

**Comment by naveenjohnsonv** [comment]
Looks like it's resolved from my end.
